INSERT INTO public.teams (team_id, team_name) VALUES (1, 'Arsenal');
INSERT INTO public.teams (team_id, team_name) VALUES (2, 'Aston Villa');
INSERT INTO public.teams (team_id, team_name) VALUES (3, 'Bournemouth');
INSERT INTO public.teams (team_id, team_name) VALUES (4, 'Brentford');
INSERT INTO public.teams (team_id, team_name) VALUES (5, 'Brighton');
INSERT INTO public.teams (team_id, team_name) VALUES (6, 'Chelsea');
INSERT INTO public.teams (team_id, team_name) VALUES (7, 'Crystal Palace');
INSERT INTO public.teams (team_id, team_name) VALUES (8, 'Everton');
INSERT INTO public.teams (team_id, team_name) VALUES (9, 'Fulham');
INSERT INTO public.teams (team_id, team_name) VALUES (10, 'Ipswich');
INSERT INTO public.teams (team_id, team_name) VALUES (11, 'Leicester');
INSERT INTO public.teams (team_id, team_name) VALUES (12, 'Liverpool');
INSERT INTO public.teams (team_id, team_name) VALUES (13, 'Manchester City');
INSERT INTO public.teams (team_id, team_name) VALUES (15, 'Newcastle');
INSERT INTO public.teams (team_id, team_name) VALUES (16, 'Nottingham');
INSERT INTO public.teams (team_id, team_name) VALUES (17, 'Southampton');
INSERT INTO public.teams (team_id, team_name) VALUES (18, 'Tottenham');
INSERT INTO public.teams (team_id, team_name) VALUES (19, 'West Ham');
INSERT INTO public.teams (team_id, team_name) VALUES (20, 'Wolves');
INSERT INTO public.teams (team_id, team_name) VALUES (14, 'Manchester United');
